drop table ingredients if exists;



drop table dogs if exists;
create table dogs (
	id_dog integer, 
	name varchar(20),
	age smallint,
	sex varchar(10),
	dead boolean
);

alter table dogs add constraint pk_dogsid primary key (id_dog,name);
alter table dogs alter column id_dog integer generated by default as identity(start with 100);


drop table pizzas if exists;
create table pizzas (
	id integer, 
	name varchar(20),
	price float
);

alter table pizzas add constraint pk_pizzasid primary key (id);

drop sequence seq_pizza if exists;
create sequence seq_pizza start with 100;


drop table apoyo if exists;
create table apoyo (
	key varchar(20) primary key,
	value varchar(20)
);


drop table exps if exists;
create table exps (
    any_exp smallint,
    num_exp integer,
    text varchar(50) not null,
    data_ini timestamp not null,
    sex varchar(10) not null,
    id_fase smallint not null,
    codi_fase varchar(20) not null
);
alter table exps add constraint pk_expsid primary key (any_exp, num_exp);
drop sequence seq_exp if exists;
create sequence seq_exp start with 100;
