package org.fijoles.mapper;

import java.sql.ResultSet;

import org.fijoles.mapper.autogen.Generator;
import org.fijoles.mapper.handler.Handler;

public class Column {

    final boolean id;
    final String columnName;

    /* private /* TODO */final Accessor accessor;

    final Handler handler;
    final Generator generator;

    public Column(boolean id, String columnName, Accessor accessor, Handler handler, Generator generator) {
        super();
        this.id = id;
        this.columnName = columnName;
        this.accessor = accessor;
        this.handler = handler;
        this.generator = generator;

        if (!id && generator != null) {
            throw new RuntimeException("autogenerated feature is only allowed for Id-typed columns");
        }
    }

    public Object getValueForJdbc(Object entity) {
        Object javaValue = accessor.get(entity);
        return handler.getJdbcValue(javaValue);
    }

    public Object getValueForJdbc(Object entity, int propertyPathIndex) {
        Object javaValue = accessor.get(entity, propertyPathIndex);
        return handler.getJdbcValue(javaValue);
    }

    public Object convertValueForJdbc(Object javaValue) {
        return handler.getJdbcValue(javaValue);
    }

    public void loadValue(Object entity, ResultSet rs) {
        try {
            Object value = handler.readValue(rs, columnName);
            accessor.set(entity, value);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    public boolean isId() {
        return id;
    }

    public String getPropertyName() {
        return accessor.getPropertyName();
    }

    public Class<?> getPropertyType() {
        return accessor.getPropertyFinalType();
    }

    public String getColumnName() {
        return columnName;
    }

    public Generator getGenerator() {
        return generator;
    }

    @Override
    public String toString() {
        return "Column [id=" + id + ", columnName=" + columnName + ", accessor=" + accessor + ", handler=" + handler
                + ", generator=" + generator + "]";
    }

}