drop table film_actor if exists;
drop table actors if exists;
drop table films if exists;


create table films (
 id integer	/* id */ ,
 title varchar(100)	/* title */ ,
 year smallint	/* year */ 
);
alter table films add constraint pk_films primary key (id);
drop sequence seq_film if exists;
create sequence seq_film start with 100;
create table actors (
 id smallint	/* id */ ,
 name varchar(100)	/* name */ 
);
alter table actors add constraint pk_actors primary key (id);
alter table actors alter column id smallint generated by default as identity(start with 100);
create table film_actor (
 id_film integer	/* id.idFilm */ ,
 id_actor smallint	/* id.idActor */ 
);
alter table film_actor add constraint pk_film_actor primary key (id_film,id_actor);


alter table film_actor add foreign key (id_film) references films(id);
alter table film_actor add foreign key (id_actor) references actors(id);

