drop table dogs if exists;
create table dogs (
	id_dog integer, 
	name varchar(20),
	age smallint,
	sex varchar(10),
	dead boolean
);

alter table dogs add constraint pk_dogsid primary key (id_dog,name);
alter table dogs alter column id_dog integer generated by default as identity(start with 100);
