drop table dogs if exists;
create table dogs (
	id_dog integer, 
	name varchar(20),
	age smallint,
	sex varchar(10),
	dead boolean
);

alter table dogs add constraint pk_dogsid primary key (id_dog,name);
alter table dogs alter column id_dog integer generated by default as identity(start with 100);


drop table pizzas if exists;
create table pizzas (
	id integer, 
	name varchar(20),
	price float
);

alter table pizzas add constraint pk_pizzasid primary key (id);

drop sequence seq_pizza if exists;
create sequence seq_pizza start with 100;


drop table apoyo if exists;
create table apoyo (
	key varchar(20) primary key,
	value varchar(20)
);