
drop table usuaris if exists;
drop table opcions if exists;
drop table votacions if exists;


create table usuaris (
 hash_usuari varchar(100)	/* id.hashUsuari */ ,
 hash_votacio varchar(100)	/* id.hashVotacio */ ,
 email varchar(100)	/* email */ ,
 alias varchar(100)	/* alias */ ,
 id_opcio_votada integer	/* idOpcioVotada */ ,
 data_votacio timestamp	/* dataVotacio */ 
);
alter table usuaris add constraint pk_usuaris primary key (hash_usuari,hash_votacio);



create table opcions (
 id_opcio integer unique	/* id.idOpcio */ ,
 hash_votacio varchar(100)	/* id.hashVotacio */ ,
 nom varchar(100)	/* nom */ ,
 descripcio varchar(100)	/* descripcio */ 
);
alter table opcions add constraint pk_opcions primary key (id_opcio,hash_votacio);
alter table opcions alter column id_opcio integer generated by default as identity(start with 100);



create table votacions (
 hash_votacio varchar(100)	/* hashVotacio */ ,
 nom varchar(100)	/* nom */ ,
 descripcio varchar(100)	/* descripcio */ ,
 data_inici timestamp	/* dataInici */ ,
 data_fi timestamp	/* dataFi */ 
);
alter table votacions add constraint pk_votacions primary key (hash_votacio);




alter table usuaris add foreign key (hash_votacio) references votacions(hash_votacio);
alter table opcions add foreign key (hash_votacio) references votacions(hash_votacio);
alter table usuaris add foreign key (id_opcio_votada) references opcions(id_opcio);


/*
org.lechuga.jdbc.exception.LechugaException: alter table usuaris add foreign key (id_opcio_votada) references opcions(id_opcio); -- []
	at org.lechuga.jdbc.JdbcDataAccesFacade.update(JdbcDataAccesFacade.java:246)
	at org.lechuga.jdbc.util.SqlScriptExecutor.execute(SqlScriptExecutor.java:33)
	at org.lechuga.jdbc.util.SqlScriptExecutor.runFromClasspath(SqlScriptExecutor.java:28)
	at org.lechuga.jdbc.util.SqlScriptExecutor.runFromClasspath(SqlScriptExecutor.java:21)
	at examples.ex3.votr.VotrTest.before(VotrTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: java.sql.SQLSyntaxErrorException: a UNIQUE constraint does not exist on referenced columns: OPCIONS in statement [alter table usuaris add foreign key (id_opcio_votada) references opcions(id_opcio)]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.executeUpdate(Unknown Source)
	at org.lechuga.jdbc.JdbcDataAccesFacade.update(JdbcDataAccesFacade.java:244)
	... 27 more
Caused by: org.hsqldb.HsqlException: a UNIQUE constraint does not exist on referenced columns: OPCIONS
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.TableWorks.checkCreateForeignKey(Unknown Source)
	at org.hsqldb.TableWorks.addForeignKey(Unknown Source)
	at org.hsqldb.StatementSchema.getResult(Unknown Source)
	at org.hsqldb.StatementSchema.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 30 more


 */
*/